# Generated by Django 5.1.7 on 2025-03-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fill_status',
            field=models.CharField(choices=[('Not filled', 'Not filled'), ('Filled', 'Filled')], default='Pending', max_length=20),
        ),
    ]
